export const disease={
    Barley_bgraminisbarley: "Powder mildew",
    Barley_fgramineadrum: "Fusarium head blight",
    Barley_psyringaeatrofaciens: "Basal glume rot",
    Barley_pgramini: "Stem rust",
    Barley__pteres: "Net blotch",
    Foxtail_aavenae: "Bacterial leaf stripe",
    Maize_bmaydis: "Southern corn leaf blight",
    Maize_czeaemydis: "Gray leaf spot",
    Maize_psorghi: "Common rust",
    Maize_umydis: "Corn smut",
    Maize_xvasicola: "Bacterial leaf streak",
    Oat_bgraminisef2: "Powdery mildew",
    Oat_cgraminicola: "Anthracnode",
    Oat_fpoae: "Fusarium head blight",
    Oat_pcoronafaciens: "Halo Blight",
    Oat_pcoronta: "leaf rust",
    Rice_boryzae: "Brown leaf spot",
    Rice_bglumae: "Bacterial panicle blight",
    Rice_moryzae: "Rice blast",
    Rice_rsolani: "Sheath blight",
    Rice_xoryzae: "Bacterial blight",
    Rye_bgraminisef2: "Powdery mildew",
    Rye_cgraminicola: "Anthracnose",
    Sorghum_cgraminicola: "Anthracnose",
    Sorghum_mphaseolina: "Charcoal rot",
    Sorghum_psyringae: "Bacterial spot",
    Wheat_bgraminiswheat: "Powdery mildew",
    Wheat_psyringaewheat: "Bacterial leaf blight",
    Wheat_pgramini: "Stem rust",
    Wheat_pstriiformis: "Stripe rust",
    Wheat_ptriticina: "Leaf rust",
    Wheat_tindica: "Karnal bunt",
    Ragi_mgrisea:"Blast",
    Ragi_meleuinis:"Smut",
    Ragi_smacrospora:"Downy mildew",
    Ragi_ueragrostidis:"Rust",
    Ragi_xeleusinae:"Bacterial leaf spot",
    Quinoa_pfarinosa: "Downy mildew",
    Quinoa_pexifua:	"Brown stalk rot",
    Quinoa_ahyalospora:"Leaf spot",
    Quinoa_srolfsii: "Seed rot",
    Quinoa_pzingerberum: "Damping off"
}


