export const disease={
    Barley_bgraminisbarley: "Powder mildew",
    Barley_fgramineadrum: "Fusarium head blight",
    Barley_psyringaeatrofaciens: "Basal glume rot",
    Barley_pgramini: "Stem rust",
    Barley__pteres: "Net blotch",
    Foxtail_aavenae: "Bacterial leaf stripe",
    Maize_bmaydis: "Southern corn leaf blight",
    Maize_czeaemydis: "Gray leaf spot",
    Maize_psorghi: "Common rust",
    Maize_umydis: "Corn smut",
    Maize_xvasicola: "Bacterial leaf streak",
    Maize_cgraminicola:	"Anthracnose",
    Maize_eturcica:	"Northern corn leaf blight",
    Maize_psyringaewheat:"Holcus spot",
    Oat_bgraminisef2: "Powdery mildew",
    Oat_cgraminicola: "Anthracnode",
    Oat_fpoae: "Fusarium head blight",
    Oat_pcoronafaciens: "Halo Blight",
    Oat_pcoronta: "leaf rust",
    Rice_boryzae: "Brown leaf spot",
    Rice_bglumae: "Bacterial panicle blight",
    Rice_moryzae: "Rice blast",
    Rice_rsolani: "Sheath blight",
    Rice_xoryzae: "Bacterial blight",
    Rye_bgraminisef2: "Powdery mildew",
    Rye_cgraminicola: "Anthracnose",
    Rye_utritici:"Loose smut",
    Rye_pteres: "Net blotch",
    Rye_cpurpurea: "Ergot",
    Sorghum_cgraminicola: "Anthracnose",
    Sorghum_mphaseolina: "Charcoal rot",
    Sorghum_psyringae: "Bacterial spot",
    Sorghum_psorghi: "Sorghum downy mildew",
    Sorghum_eturcica: "Leaf blight",
    Wheat_bgraminiswheat: "Powdery mildew",
    Wheat_psyringaewheat: "Bacterial leaf blight",
    Wheat_pgramini: "Stem rust",
    Wheat_pstriiformis: "Stripe rust",
    Wheat_ptriticina: "Leaf rust",
    Wheat_tindica: "Karnal bunt",
    Wheat_ztritici:"Septoria leaf blotch",
    Wheat_ptriticirep:"Tab spot",
    Wheat_tcaries:"Common bunt",
    Wheat_tlaevis: "Common bunt",
    Wheat_utritici:"Loose smut",
    Wheat_tcontroversa:"Dwarf bunt",
    Wheat_fgramineadrum:"Fusarium head blight",
    Ragi_pfarinosa: "Blast",
    Ragi_pgriesea: "Ragi Blast ",
    Quinoa_pgriesea: "Downy mildew",
    Quinoa_meleuinis: "Brown stalk rot",
}


